spring:
  application:
    name: hp-gnss-gather
# spring 集成kafka配置
  kafka:
    producer:
      retries: 0 #重试次数
      batch-size: 16384 # 批处理大小
      buffer-memory: 33554432
      key-serializer: com.longge.gather.kafka.fastjson.FastJsonSerializer
      value-serializer: com.longge.gather.kafka.fastjson.FastJsonSerializer
      linger: 5 #延迟发送时间
      bootstrap-servers: 10.30.0.106:9092
com:
  longge:
    netty:
       socketType: server #socket类型
       socketProtocol: qxrtcm3.2 #协议名称
       socketKeepalive: false #Socket参数，连接保活，默认值为False。启用该功能时，TCP会主动探测空闲连接的有效性。可以将此功能视为TCP的心跳机制，需要注意的是：默认的心跳间隔是7200s即2小时。Netty默认关闭该功能
       socketReuseaddr: true #地址复用，默认值False。有四种情况可以使用：(1).当有一个有相同本地地址和端口的socket1处于TIME_WAIT状态时，而你希望启动的程序的socket2要占用该地址和端口，比如重启服务且保持先前端口。(2).有多块网卡或用IP Alias技术的机器在同一端口启动多个进程，但每个进程绑定的本地IP地址不能相同。(3).单个进程绑定相同的端口到多个socket上，但每个socket绑定的ip地址不同。(4).完全相同的地址和端口的重复绑定。但这只用于UDP的多播，不用于TCP。
       socketTcpNodelay: true #TCP参数，立即发送数据，默认值为Ture（Netty默认为True而操作系统默认为False）。该值设置Nagle算法的启用，改算法将小的碎片数据连接成更大的报文来最小化所发送的报文的数量，如果需要发送一些较小的报文，则需要禁用该算法。Netty默认禁用该算法，从而最小化报文传输延时。
       socketBacklog: 1024 #  Socket参数，服务端接受连接的队列长度，如果队列已满，客户端连接将被拒绝
       socketSndbuf: 10485760 # Socket参数，TCP数据发送缓冲区大小。
       socketRevbuf: 10485760 # Socket参数，TCP数据接收缓冲区大小。
       socketRead: 120 #读超时时间
       socketWrite: 120 #写超时时间
       socketReadAndWrite: 120 #读写超时时间
       socketSsl: false #使用ssl加密
       socketJksFile: /securesocket.jks #ssl 加密 jks文件地址
       socketJksStorePassword: jianglong #读取jks密码
       socketjksCertificatePassword: jianglong #读取私钥密码
       serverPort: 8082 #端口
       serverBossThread: 1  #用于处理客户端的连接请求
       serverWorkThread: 4  #用于处理与各个客户端连接的IO操作
       serverPeriod: 10  #扫描频次
       clientBossThread: 1
       clientConnectTime: 3000 # 链接超时
       clientMaxTimes: 0 #最大重连次数，赋值小于1表示无限次数。
       clientPeriod: 5000 #重连间隔时间，毫秒
    threadpool:
      corePoolSize: 1 #配置核心线程数
      maxPoolSize: 50 #配置最大线程数
      poolQueueCapacity: 500 #配置队列大小
      threadNamePrefix: kafkaProducers_thread #配置线程池中的线程的名称前缀
      visiblePool: false #是否打印线程信息
      visibleLog: false #是否打印日志
      listenerQueueSize: 100000 #生产监听者队列大小