server:
  port: 8080
  #servlet:
    #context-path: /authweb
spring:
  application:
    name: authweb
    instanceId: 127.0.0.1:8080
  profiles:
    active: dev
    metrics:
      servo:
        enabled: false
logging:
  config: classpath:log4j2.xml
---
spring:
  profiles: dev
  dubbo:
    application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
      name: userConsumer
    registry:                 #注册中心配置，用于配置连接注册中心相关信息。
      address: zookeeper://10.30.0.41:2181
    protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受（订阅）
      name: dubbo
      port: 20880
    consumer:
      check: false
      reference: 
        loadbalance: roundrobin #轮询机制
       #loadbalance: random #随机机制
       #loadbalance: leastactive #最少活跃调用数机制
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:jianglong@10.30.0.41:1111/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instanceId}:${server.port}
    appname: ${spring.application.name}
    healthcheck:
      enabled: true